import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'
import gsap from 'gsap'
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import { useLayoutEffect, useRef } from 'react'
import SoloWork from '@component/components/solowork'
import Link from 'next/link'

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);
  const app = useRef();
  
  useLayoutEffect(() => {
    let ctx = gsap.context(() => {
      gsap.to("#hero h1 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        stagger:0.2,
        ease:"easeOut"
      });

      gsap.to("#about h2 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#about h2",
        }
      });

      gsap.to("#about h3 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#about h3",
        }
      });

      gsap.from("#about p", { 
        opacity:0,
        duration:1,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#about p",
        }
      });

      gsap.from("#easy", { 
        rotate:"0deg",
        x:375,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#aboutimgset",
          start: "center bottom",
          end: "bottom center",
          scrub: true
        }
      });

      gsap.from("#goodbye", { 
        top:"0px",
        rotate:"0deg",
        x:125,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#aboutimgset",
          start: "center bottom",
          end: "bottom center",
          scrub: true
        }
      });

      gsap.from("#watercolor", {
        rotate:"0deg", 
        x:-125,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#aboutimgset",
          start: "center bottom",
          end: "bottom center",
          scrub: true
        }
      });

      gsap.from("#makemehappy", { 
        top:"0px",
        rotate:"0deg",
        x:-375,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#aboutimgset",
          start: "center bottom",
          end: "bottom center",
          scrub: true
        }
      });

      gsap.to("#discography-desc h2 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        delay:0.2,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#discography-desc h2",
        }
      });

      gsap.to("#solowork h2 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        delay:0.2,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#solowork h2",
        }
      });

      gsap.from("#discography-desc p", { 
        opacity:0,
        duration:1,
        
        delay:0.2,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#discography-desc p",
        }
      });
      
      gsap.to("#discography", { 
        backgroundColor:"#292B31",
        color:"#F0F2F6",
        scrollTrigger:{
          trigger:"#discography-desc h2",
          start: "top",
          end: "bottom",
          scrub: true
        }
      });

      gsap.to("#vocals h2 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        delay:0.2,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#vocals h2",
        }
      });

      gsap.from("#vocals p", { 
        opacity:0,
        duration:1,
        
        delay:0.2,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#vocals p",
        }
      });

      gsap.to("#dance h2 .line", { 
        y: "0%" ,
        opacity:"1",
        duration:1,
        delay:0.2,
        stagger:0.2,
        ease:"easeOut",
        scrollTrigger:{
          trigger:"#dance h2",
        }
      });

      gsap.from("#dance p", { 
        opacity:0,
        duration:1,
        
        delay:0.2,
        ease:"SlowMo.easeInOut",
        scrollTrigger:{
          trigger:"#dance p",
        }
      });

    }, app);
    
    return () => ctx.revert();
  }, []);
  return (
    <>
      <Head>
        <title>Happy Wheein Day 🦋</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main id="main" ref={app} className={styles.main}>
        <div className={styles.responsivenotif}>
          <span>Mobile version in progress! Please use a tablet &#40;landscape&#41; or desktop for best experience!</span>
        </div>
        <article id="hero" className={styles.hero}>
          <h1 id="herotext" className={styles.herotext}>
            <div>
              <span class="line">On April 17, 1995, in Jeonju,</span>
            </div>
            <div>
            <span class="line">Jeollabuk-do, South Korea,</span>
            </div>
            <div>
              <span class="line">a <i>butterfly </i>is born.</span>
            </div>
          </h1>
          <div className={styles.herogallery}>
          </div>
        </article>

        <article id="about" className={styles.about}>
          <h2>
            <div>
                <span class="line">She is a butterfly who flies swiftly as the wind.</span>
            </div>
          </h2>
          
          <section id="aboutimgset" className={styles.aboutimgset}>
            <div id="easy" className={styles.imgcontainer} style={{rotate:"-5deg"}}>
              <Image src="/images/solopics/easy.png" layout="fill"/>
            </div>
            <div id="goodbye" className={styles.imgcontainer} style={{rotate:"5deg", position:"relative", top:"50px"}}>
              <Image src="/images/solopics/goodbye.png" layout="fill" />
            </div>
            <div id="watercolor" className={styles.imgcontainer} style={{rotate:"-5deg"}}>
              <Image src="/images/solopics/watercolor.png" layout="fill"/>
            </div>
            <div id="makemehappy" className={styles.imgcontainer} style={{rotate:"5deg", position:"relative", top:"50px"}}>
              <Image src="/images/solopics/makemehappy.png" layout="fill"/>
            </div>
          </section>
          
          <section className={styles.aboutdesc}>
            <h3>
              <div>
                  <span class="line">JUNG WHEEIN &#40;정휘인&#41;</span>
              </div>
            </h3>
            <p>is a South Korean singer under The L1ve. She is best known as a member of South Korean girl group MAMAMOO, where she is focused on vocals and performance.</p>
          </section>
        </article>

          <article id="discography" className={styles.discography}>
            <section id="discography-desc" >
              <h2>
                <div>
                    <span class="line">Wheein is well-known and appreciated by her </span>
                </div>
                <div>
                    <span class="line">honey vocals. From calm, relaxing love songs, to </span>
                </div>
                <div>
                    <span class="line">touching, powerful ballads.</span>
                </div>
              </h2>

              <p>She is also considered the backbone of MAMAMOO, as she provides support during their vocal performances. As a background vocal doing adlibs or the center of attention, Wheein is able to bring a unique flavor into every song.</p>
            </section>
            
            
            
            <section id="solowork" className={styles.solowork}>
            <h2>
              <div>
                <span class="line">SOLO WORK</span>
              </div>
            </h2>
            <div id="sololist" className={styles.sololist}>
              <SoloWork props={
                {
                  title:"Magnolia",
                  image:'/images/soloalbums/magnolia.webp',
                  date:"April 17, 2018",
                  tracks:[
                    {
                        "title":"Easy (feat. Sik-K)",
                        "time":"3:08"
                    }
                  ],
                  titletrack:"Easy",
                  spotify:"https://open.spotify.com/track/35Bon0pO4syTi6Hfsr2Kk8?si=d1fd6f4d4694442d",
                  youtube:"https://youtu.be/U_tQ-GIC0O8",
                }
              }/>
              <SoloWork props={
                {
                  title:"Soar",
                  image:'/images/soloalbums/soar.webp',
                  date:"April 17, 2018",
                  tracks:[
                    {
                        "title":"Goodbye",
                        "time":"4:12"
                    }
                    ],
                  titletrack:"Goodbye",
                  spotify:"https://open.spotify.com/track/35Bon0pO4syTi6Hfsr2Kk8?si=d1fd6f4d4694442d",
                  youtube:"https://youtu.be/U_tQ-GIC0O8",
                }
              }/>
              <SoloWork props={
                {
                  title:"Redd",
                  image:'/images/soloalbums/redd.webp',
                  date:"April 17, 2018",
                  tracks:[
                    {
                        "title":"water color",
                        "time":"3:09"
                    },
                    {
                        "title":"TRASH (Feat. pH-1)",
                        "time":"2:52"
                    },
                    {
                        "title":"OHOO",
                        "time":"3:16"
                    },{
                        "title":"Butterfly (Feat. GSoul)",
                        "time":"3:28"
                    },
                    {
                        "title":"Springtime",
                        "time":"2:40"
                    },
                    {
                        "title":"NO THANKS",
                        "time":"3:52"
                    }
                    ],
                  titletrack:"Watercolor",
                  spotify:"https://open.spotify.com/track/35Bon0pO4syTi6Hfsr2Kk8?si=d1fd6f4d4694442d",
                  youtube:"https://youtu.be/U_tQ-GIC0O8",
                }
              }/>
              <SoloWork props={
                {
                  title:"WHEE",
                  image:'/images/soloalbums/whee.webp',
                  date:"April 17, 2018",
                  tracks:[
                    {
                        "title":"Make Me Happy",
                        "time":"3:17"
                    },
                    {
                        "title":"Pink Cloud",
                        "time":"3:01"
                    },
                    {
                        "title":"Letter Filled With Light",
                        "time":"3:08"
                    },{
                        "title":"Deserve (Interlude)",
                        "time":"0:32"
                    },
                    {
                        "title":"Pastel",
                        "time":"2:22"
                    },
                    {
                        "title":"Paraglide",
                        "time":"3:38"
                    }
                    ],
                  titletrack:"Make Me Happy",
                  spotify:"https://open.spotify.com/track/35Bon0pO4syTi6Hfsr2Kk8?si=d1fd6f4d4694442d",
                  youtube:"https://youtu.be/U_tQ-GIC0O8",
                }
              }/>
            </div>
            </section>

            <section id="vocals" className={styles.vocals}>
              <h2>
                <div>
                  <span class="line">Vocal Showcase</span>
                </div>
              </h2>
              <p>Listen with headphones/earphones for best experience!</p>
              
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/ydsuc1vOavw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/6l4divMKp4E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/2wcAbpYfj5c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/AzPgpPe1RHA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/VzpxvsrupkY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <div className={styles.vocalyoutube}>
                  <iframe width="100%" height="100%" src="https://www.youtube.com/embed/bOnMQ9OmfAk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
              
            </section>

            <section id="dance" className={styles.dance}>
              <h2>
                <div>
                    <span class="line">Aside from vocals, Wheein is also </span>
                </div>
                <div>
                    <span class="line">great in dancing and performing!</span>
                </div>
              </h2>
              <p>
              As part of the performance line, Wheein is shown to be very skillful in dancing. She is able to do cool moves for hip-hop songs, to alluring moves for mature concepts.
              </p>
            </section>
            <section className={styles.end}>
              <h2>YOU&#39;VE REACHED THE END OF THE SITE!</h2>
              <h2>The site is still work in progress. To further improve the site until completion, you may share feedback or suggestions to <Link href="https://twitter.com/loafsprout">@loafsprout!</Link></h2>
            </section>
          </article>
          
      </main>
    </>
  )
}
